[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
twizzin_be_v2 = "6tssgoTwAU88td3wXkj2xFj8Q2QpfsBsBGK4HJxrwhYs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
