name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  SOLANA_VERSION: 1.17.0
  ANCHOR_VERSION: 0.28.0
  NODE_VERSION: 18.x

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache Solana Tool Suite
        uses: actions/cache@v3
        id: cache-solana
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana/install
          key: solana-${{ runner.os }}-v${{ env.SOLANA_VERSION }}

      - name: Install Solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install ${{ env.ANCHOR_VERSION }}
          avm use ${{ env.ANCHOR_VERSION }}

      - name: Generate Anchor IDL
        run: anchor build

      - name: Install Dependencies
        run: yarn install

      - name: Start Local Validator
        run: solana-test-validator --reset --quiet &

      - name: Wait for Validator
        run: sleep 5

      - name: Run Tests
        run: |
          anchor test
          if [ $? -ne 0 ]; then
            echo "Tests failed. Displaying validator logs:"
            cat test-ledger/validator.log
            exit 1
          fi

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Upload Test Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            test-ledger/validator.log
            target/deploy/*.log
