[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
twizzin_be = "DPkdxvGPH81zodC8LnSg3xnhEKABSCadE5ifxNWwsQ6Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
